name: Deploy Project

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Apache Maven Central
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: 'ossrh'
        server-usename: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Publish to Maven Central
      run: mvn deploy
      env:
        MAVEN_USERNAME: ascendise
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}